name: Android Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-${{ runner.os }}-

      - name: Cache Buildozer directory in app
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ github.run_id }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Create NDK Directory
        run: mkdir -p ~/.buildozer/android/platform

      - name: Download Android NDK (r25b)
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O /tmp/android-ndk-r25b-linux.zip

      - name: Unzip Android NDK
        run: unzip /tmp/android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/android-ndk-r25b

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libunwind-dev zlib1g-dev
          sudo apt-get install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev uuid-dev libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
          sudo apt-get install -y zip unzip autoconf libtool pkg-config libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev automake

      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Keep your preferred Python version

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 git+https://github.com/kivy/plyer.git

      - name: Build with Buildozer
        id: buildozer
        run: yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            bin/*.apk
            bin/*.aab
          retention-days: 3
