name: Build APK

on:
  push:
    branches:
      - main  # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        sudo apt install -y libffi-dev libssl-dev
        mkdir -p bin  # Ensure the bin directory exists
        buildozer android debug
        ls -al bin  # Debugging: Verify APK is generated

    - name: Send APK via Email
      env:
        RECIPIENT_EMAIL: abhinandanroy165@gmail.com
      run: |
        sudo apt install -y mailutils
        APK_PATH=$(ls bin/*.apk | head -n 1)
        if [ -f "$APK_PATH" ]; then
          echo "Sending APK to ${RECIPIENT_EMAIL}"
          echo "Here is your APK file." | mailx -s "Your APK File" -a "$APK_PATH" "${RECIPIENT_EMAIL}"
        else
          echo "APK file not found. Email not sent." && exit 1
