name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64

      - name: Set up Java 17 (required for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo6 \
            cmake libffi-dev libssl-dev \
            libtinfo5  # Add libtinfo5 here

      - name: Upgrade pip and install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install Cython==0.29.33 buildozer

      - name: Install app requirements (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            echo "Installing from requirements.txt..."
            python3 -m pip install -r requirements.txt
          else
            echo "No requirements.txt found."
          fi

      - name: Build APK with Buildozer
        run: |
          echo "Running buildozer android debug"
          buildozer android debug
