name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip python3-pip \
                            openjdk-8-jdk libffi-dev libssl-dev \
                            libncurses6 libstdc++6 python3-dev
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        pip install --upgrade pip
        pip install buildozer cython kivy

    - name: Build APK
      run: |
        mkdir -p bin
        buildozer android clean
        buildozer android debug || { echo "Buildozer failed!"; cat buildozer.spec; exit 1; }
        ls -al bin

    - name: Send APK via Email
      env:
        RECIPIENT_EMAIL: abhinandanroy165@gmail.com
      run: |
        sudo apt install -y mailutils
        APK_PATH=$(ls bin/*.apk | head -n 1)
        if [ -f "$APK_PATH" ]; then
          echo "Sending APK to ${RECIPIENT_EMAIL}"
          echo "Here is your APK file." | mailx -s "Your APK File" -a "$APK_PATH" "${RECIPIENT_EMAIL}"
        else
          echo "APK file not found. Email not sent." && exit 1
