name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Update apt and Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6

      - name: Install sdkmanager
        run: |
          sudo apt-get install -y unzip openjdk-17-jdk wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv $HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk # Define ANDROID_HOME

      - name: Set up environment variables
        run: |
          echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Check Java version
        run: java -version

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk # Assuming buildozer places the APK in the ./bin directory
