name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git wget libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Pre-accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true

      - name: Initialize Buildozer
        run: |
          buildozer android clean

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app.apk
          path: bin/*.apk
